---
- name: Install and Configure HTTPD
  hosts: all
  become: true
  vars:
    s3_image_urls:
      - "https://group-7-staging.s3.us-east-1.amazonaws.com/Group7.jpg?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEG4aCXVzLWVhc3QtMSJGMEQCIA6MprVylkIvkWvAAvTelwdWDtTgoqy7tdTNg0gaqVU%2BAiBrB4zEV8mDHaRTbn0W6i7WxgqQ%2B6shwiwtCplOBoNnGSrQAwgmEAAaDDM5MTM1NjYyNzU4NyIMNmNoQa%2FDIT6NT2KxKq0Duv1V5JJoTj3hApZoYRo%2F8LKMVRWViT%2Fre%2FaszYhU5Oi5JhjANQeDYbIsBtq9CQpO9YbWSi1WdvPvNEBNVJk1U%2BLDO4Q1ByZ06HU6RMBwUTdvx9TRuNgRJf64s2onU4oYBtQf9WrV5Lg1j8xzq0VaVGTnBGVs%2BohzsSAM%2BRHHE6R5OPOL7z110X%2FHBi%2FdE8D0CBz1VYuI7vYHwQVjwQO9ytZne%2Frt9rAVsk5IWWCI2RTNADvoYgK5YvrbqoOau%2BdkdG4z7MuIcI9REc7UfZIjDXaHewmnvo7gdanTO1iEw4f9JBXYdWEYeXQHJBrdpRZAEn0n4Gc08lRVwN2I9%2FVa%2Bi2NhvlpP6AleaWhgK7AqD%2FGyc6P5cyXA%2Fw6II4AYnJUD2OGv6kkd4M6kuvEE0XBpA3fk5lIsVvMAD5nWBnCfWs4Cugx8kSwo3SIa%2BxjvYbCcyO7pTaP4YxPKGS%2BcY57b2T83qlAfrTWVX1Flw%2F7Cc1mTWaP6GAZyU4zURfB1dqryzofYBiQ3LtHPss5yWjuONiK9L9dF4lWSUSYy1j0EKdHL4H5w9FgSzRemX6PMIX8yboGOrgCfK2PVN4xBGtH7iALHzNo9RwHNBsawia1uOyAA0z6H2NIIYmav0X%2BZn6mPs1QdrVHIEZLsAOCOvDcfV%2Fyg7seuJGD2NGxWsG7N1%2BFHlZ%2ByscHovBHQRBFjxDJS%2BqTboNkuSsORklLVEiaiIRQm7EqWJRKPpNg1j%2BdgBM29v0drw%2FVvpG%2BbegPqui%2B29bR9g1GBTxxbrveS1bcypU3rKZ6BuLxUyII3BGmz0bdCNfi0%2BhpP6c%2Bn98B1TzesPMao48lvQZdibzNpIXlXTB8wow1RNz6rqJ7TZ4gKGglL1nTlcicVBR5c3RdDfSvixkP9CN609FJ0fd3UtRKeNCOKaC8JKE3HD7OhjEdMbDnT6YgcWJ%2Fx%2BXzOAO614TGPUfpsS1YuJjuGPa8M9M7ZKYaxaKQB4PoAYKewMR2&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAVWHVMHKB2XLYJBYK%2F20241206%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241206T050941Z&X-Amz-Expires=14400&X-Amz-SignedHeaders=host&X-Amz-Signature=54701ec3995b378a1406c6552a3f717bbf98a14c9d800c1e9fcdc03a97dbe899"
    team_members:
      - "Ishan Sohal"
      - "Vishnu Reghunath"
      - "Rony Hopeman"
      - "Yash Gujral"
  tasks:
    - name: Update the system packages
      yum:
        name: '*'
        state: latest

    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start and enable HTTPD service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Fetch local IPv4 address
      uri:
        url: http://169.254.169.254/latest/meta-data/local-ipv4
        return_content: yes
      register: local_ipv4

    - name: Fetch Instance ID
      uri:
        url: http://169.254.169.254/latest/meta-data/instance-id
        return_content: yes
      register: instance_id

    - name: Fetch Availability Zone
      uri:
        url: http://169.254.169.254/latest/meta-data/placement/availability-zone
        return_content: yes
      register: availability_zone

    - name: Get current server time
      shell: date
      register: current_time

    - name: Create the index.html file from template
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      vars:
        myip: "{{ local_ipv4.content }}"
        instance_id: "{{ instance_id.content }}"
        availability_zone: "{{ availability_zone.content }}"
        current_time: "{{ current_time.stdout }}"

    - name: Ensure proper permissions for the web directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        recurse: yes