---
- name: Install and Configure HTTPD
  hosts: all
  become: true
  vars:
    s3_image_urls:
      - "https://group-7-staging.s3.us-east-1.amazonaws.com/Group7.jpg?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGwaCXVzLWVhc3QtMSJIMEYCIQCvl0rlih35D6YhNaXmIY6S7G9%2F8UQ3efX9soigSAJHYQIhAMYjbINOGZoxBzQlXPmmihmH%2BiSoMfrSyNfXmygjucuOKtADCCUQABoMMzkxMzU2NjI3NTg3IgxAWJPt0xw45cAe8GUqrQMTXiso%2BK8mpDIdbxUvuAhU9vdD23Jybj5RuoEXm%2FXHoR2CeTnjGhC0XziUIjYiRK12MaBssSwTGywcFlaGJGv%2FehY%2B8c7DHdqVbm0vxgQ0NI%2Fnoo8%2FNGEvvox6bRLlfbZHoh3e0m2I36jm0jVuzoMtIl%2Bc5T0PSD%2BYbwjubuK0oeTVSWjZAGUaBKUQvppExVj5DpKKiG6fPrjdP0L9tdHM3t8uhoOi7rTT1nbKJy%2Fp%2F0ZJrmHcuivf8I3SBNJuFPHPR%2FNmhhjKi2cfq6MqCmC3mVpmawqtDkHOVyTzrHX9DZ0xaho5gXELodY1qBGh2QbyYmvZENZU3Ij9njaKnnua66OKn4UvIG9DDrJG456N0v7Bx%2FmzE6adruFJ39VXUvuPJpCqDDsAJdM6ReyXH6whPKcbFPnZZDDy1GHhCOZZpUcLliPtgGujxtkqQjmu5JlM8exxwAXUx6yHK3rov6V%2FLD77OQWYv3f3Ml11MqFBiYVpXBbkPYLpGZdMykxxaptNRwv8ExiOGdZNUybJUcqW32wVOV4%2F0gIc1dg9RxiUs4tlkQGZgViUYNyLS7swrYvJugY6tgLhZChf4H8vptCyLR06oIaxjArjo3iA%2FHwVui0uGoo9evgwXvDtoM6sajcNpw8TK74tJ3EEhO9OlPsRJKTzjvRwSLLee21LaRSr9Flc5W7flxHJJDnMuwc5zTEq6J44Z%2FWhcIpT5KJdnVFMmcKp9ZMba4OLNT4D9sEtbcvxWiLWMsIGrIbFasXnDAL8CTxJ0mCJhlnpTxwTtVyv2F6WKTdI37VfckytMrRal1JZrtYXk2%2FQsu%2BKbyJ%2BN2%2BkQeekA9Dc1HxokVD7YC5Cn2Nmq72pUiuEGQfAcKUBY994%2FS7KzbMSBZsN4IGq9rH4rtYybDkFY3aLAPuwy3MZkR%2FvSQpUzng6%2BhvxiD74nbuQxx4KwtLKKLfXI0qX2uo%2FiOMGpSLelTCht77SsI3mdPoRtpBEfQDCl0oJ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAVWHVMHKBSSBSVMTL%2F20241206%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241206T034414Z&X-Amz-Expires=21600&X-Amz-SignedHeaders=host&X-Amz-Signature=27855a14cebfbb4386a1a1624f1de1a9ea9910cdd7fcb7fe25847aae8c0c4138"
    team_members:
      - "Ishan Sohal"
      - "Vishnu Reghunath"
      - "Rony Hopeman"
      - "Yash Gujral"
  tasks:
    - name: Update the system packages
      yum:
        name: '*'
        state: latest

    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start and enable HTTPD service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Fetch local IPv4 address
      uri:
        url: http://169.254.169.254/latest/meta-data/local-ipv4
        return_content: yes
      register: local_ipv4

    - name: Fetch Instance ID
      uri:
        url: http://169.254.169.254/latest/meta-data/instance-id
        return_content: yes
      register: instance_id

    - name: Fetch Availability Zone
      uri:
        url: http://169.254.169.254/latest/meta-data/placement/availability-zone
        return_content: yes
      register: availability_zone

    - name: Get current server time
      shell: date
      register: current_time

    - name: Create the index.html file from template
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      vars:
        myip: "{{ local_ipv4.content }}"
        instance_id: "{{ instance_id.content }}"
        availability_zone: "{{ availability_zone.content }}"
        current_time: "{{ current_time.stdout }}"

    - name: Ensure proper permissions for the web directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        recurse: yes