---
- name: Install and Configure HTTPD
  hosts: all
  become: true
  vars:
    s3_image_url: "https://group-7-prod.s3.us-east-1.amazonaws.com/Group7.jpg?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEG8aCXVzLWVhc3QtMSJHMEUCIDSi00uKcpV6NKz8v34PxhOK2Xpv5DI9bk9D3t95GEuEAiEA2CZRRf4HDy%2B4d3PGkR4KfUxW2cS%2FKezLbdFL8KIgVu4q0AMIKBAAGgwzOTEzNTY2Mjc1ODciDJMwVRRnL3xJ%2FNXFRSqtA4AwU%2BDENMtQEjhez%2Fi%2FmKIo0IOvXwq2YbDIkIMglu8Aknb7tEy4mHDWr8BkkZNlAqQ5S0gx%2B96XOFGXheljt2tidsEh4dGEmI602hnC2mxIAeYv%2FAoIMZc3SUzeVNC4LTZ4dB%2BFxnK1NKEPIDgBSLkkxXvk4mUJEUMBMQ%2FMclS2CIYd7txpGGU1N1p6GN8%2F91ikbaj%2FPzhu6VrtPQqiahpxgrZbRKTlNcjvWdKg9yf96XNxdiZAk1c1ysv0icpi%2B7zKioFuwRIgVGdSrpFMEF0g7sIcBeXXYMaS4QoMigC1%2FBhkfMhxSIk%2BCs04yzsK2QxQ8eYR%2F7nEWsaUB5mD08R9WZboAR7P9QhWO3anXL6PXGDngz%2BP%2BD4VV3ZuPMkZ643Djymy9ywpqFGmqJcJlre%2FmsF1nw7bSBxOVRoBI8t3%2BxXkWKFh7SRskL%2FfSPb%2BBKKcPPNchRuN%2B6em6jwLOqyOr50NBBMOZKvkU5vqpIqQVBVzKvHalUqYqePbss9fw10ULDGvLNqftuYQchaYGPQKT0ljGTqcUKK4AGsabh5fNY%2Fty5NYpxbNDmH3KzCF%2FMm6Bjq3Anju%2FVrxG%2B%2FANKMvlu43yOF2XKjuAJBXMnuri1HOiIKdDu%2FqGQ5C3x0Soa85ehd2gJoglWpTg%2FlxTkXtRAcT8eAxuI4PIxjN%2Fzz225eu2yAsI5jIPgAAvBDzdMe41DPCfMwAxEyKbZxqIyhBTrhk%2FWVkEDeqpY%2FjZG%2FM%2BH9NUe%2FEa%2BE5wpPvFOdrWiPM8RRhChsLDvyq6jbqwRH2AROr5Bb8p%2B8YI1LH9kwUX5IC2kniT9gfk6XNkVdwUdTFv8eG%2BXiXLpL8DS%2B86FrFCDVq6Jj09QDZ0olRxyZl99S64K5hp%2BejB4XZihycCXlQylD2YtAlkJQd%2Bi6i4BSPGW16NlAModIxmuxFrlFxyxPHh5Jz5fguNd8PyWzsNzgqC8AFM9B1%2Fa9tK2o1efrGUWWDXKIE2x4CMBuU&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAVWHVMHKBXX3J6ZK6%2F20241206%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241206T062237Z&X-Amz-Expires=14400&X-Amz-SignedHeaders=host&X-Amz-Signature=4d6532bc7adfcaccfbb88733b9b4fb67269c7b5f5cf1fe27b56d3fbba0a6f1cb"
    team_members:
      - "Ishan Sohal"
      - "Vishnu Reghunath"
      - "Rony Hopeman"
      - "Yash Gujral"
  tasks:
    - name: Update the system packages
      yum:
        name: '*'
        state: latest

    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start and enable HTTPD service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Fetch local IPv4 address
      uri:
        url: http://169.254.169.254/latest/meta-data/local-ipv4
        return_content: yes
      register: local_ipv4

    - name: Fetch Instance ID
      uri:
        url: http://169.254.169.254/latest/meta-data/instance-id
        return_content: yes
      register: instance_id

    - name: Fetch Availability Zone
      uri:
        url: http://169.254.169.254/latest/meta-data/placement/availability-zone
        return_content: yes
      register: availability_zone

    - name: Get current server time
      shell: date
      register: current_time

    - name: Create the index.html file from template
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      vars:
        myip: "{{ local_ipv4.content }}"
        instance_id: "{{ instance_id.content }}"
        availability_zone: "{{ availability_zone.content }}"
        current_time: "{{ current_time.stdout }}"

    - name: Ensure proper permissions for the web directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        recurse: yes