name: Trivy Security Scanning on Terraform Code

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev  

permissions:
  security-events: write  

jobs:
  trivy-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner on Terraform files
        uses: aquasecurity/trivy-action@v0.29.0  
        with:
          scan-type: 'config'         
          hide-progress: false
          format: 'sarif'             
          scan-ref: './'              
          output: 'trivy-results.sarif'
          exit-code: '1'              
          ignore-unfixed: true        

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2.1.34
        with:
          sarif_file: 'trivy-results.sarif'
