name: Terraform Linting with TFLint

on:
  push:
    branches:
      - "dev"  
  pull_request:
    branches:
      - "dev" 

jobs:
  lint:
    name: Run TFLint on Terraform Code
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v3

   
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          tflint_version: "latest"

    
      - name: Initialize and Run TFLint
        run: |
          tflint --init  
          tflint         
